//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheTennisProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheTennisProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dupliquer table année précédente
        ///extraire les codes sans doublons sous Excel
        ///vérifier les changements de tournoi sur wikipédia
        ///
        ///calculer les tournois de la liste qui ne match pas &quot;code_new&quot; de l&apos;année précédent
        ///
        ///SELECT * FROM `tournaments` join editions on tournaments.ID = editions.tournament_ID WHERE `original_code` in (
        ///[liste_du_dessus]
        ///) order by editions.year desc 
        ///
        ///récupérer les ID et préparer les transitions (exemple)
        ///320 ---&gt; eastbourne
        ///322 ---&gt; budapest
        ///259 ---&gt; Nice
        ///288 ---&gt; changeme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string procedure_manuelle_tournois {
            get {
                return ResourceManager.GetString("procedure_manuelle_tournois", resourceCulture);
            }
        }

#pragma warning disable CS1570 // XML comment has badly formed XML    
        
#pragma warning disable CS1587 // XML comment is not placed on a valid language element
/// <summary>
        ///   Looks up a localized string similar to SET SQL_MODE = &quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        ///SET time_zone = &quot;+00:00&quot;;
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        ////*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        ////*!40101 SET NAMES utf8mb4 */;
        ///
        ///CREATE DATABASE IF NOT EXISTS `the_tennis_project` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
        ///USE `the_tennis_project`;
        ///
        ///CREATE TABLE `backup_matches` (
        ///  `ID` bigint(20) UNSIGNED NOT NULL,
        ///  `original_key` varc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string the_tennis_project_DB {
#pragma warning restore CS1587 // XML comment is not placed on a valid language element
#pragma warning restore CS1570 // XML comment has badly formed XML
            get {
                return ResourceManager.GetString("the_tennis_project_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET SQL_MODE = &quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        ///SET time_zone = &quot;+00:00&quot;;
        ///CREATE DATABASE IF NOT EXISTS `the_tennis_project` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
        ///USE `the_tennis_project`;
        ///
        ///DROP TABLE IF EXISTS `editions`;
        ///CREATE TABLE IF NOT EXISTS `editions` (
        ///  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
        ///  `tourney_ID` int(10) unsigned NOT NULL,
        ///  `year` int(10) unsigned NOT NULL,
        ///  `draw_size` smallint(5) unsigned NOT NULL,
        ///  `date_begin` datetime NOT NULL,
        ///  PRIMARY KEY (`ID`),
        ///  UNIQUE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string the_tennis_project_DB_old {
            get {
                return ResourceManager.GetString("the_tennis_project_DB_old", resourceCulture);
            }
        }
    }
}
